1)"(grid and flex)"  :-  use webside layout banavnyasathi
2)vw stands for Viewport Width 
  vh stands for Viewport Height 
3)css(cascading style sheet) -
cascading-pahila kon calnar =inline ,external ,internal
style sheet - webpage la style karne (color dene)
cascading - 3 prakar yetat("external","internal","inline" ) kontya prakar pihila run karnar

"inline" -    <p style="color: red;">This text is red.</p>
"external"-  <link rel="stylesheet" href="styles.css">
"internal"-   <style>   ||| style tag takun lihane
  p { color: blue; }
</style>


4)spacifity(high prefrance) in css -
Inline style 
ID selector 
Class, attribute selectors आणि pseudo-classes
Element selectors 

5)selector in css - "id selector" , "class selector","element selector"

6)default value of posision property in css - its is "stactic"

7)box-model - mahanje element la cover kartana pading margin kiti age he box model madhi dista




