

github 2 lokanmadhi git hub kasa vapartat 


self work ====
1)new repositry create karaychi ||| readme.md la selct nahi karaychi
2)mang git tula tya comman denar je tula tuzya create keleya folder madhi takaychi 

jevha tu code change karan tevha he command tak all code github var push hoin
git add .
git commit -m "first commit"
git push origin main 



team work ====  tula jo add karicha yla access deyva lagen
1)person

1)new repositry create karaychi ||| readme.md la selct nahi karaychi
2)mang git tula tya comman denar je tula tuzya create keleya folder madhi takaychi 

jevha tu code change karan tevha he command tak all code github var push hoin
git add .
git commit -m "first commit"
git push origin main 

3)collaborators add kar  ||| mang tuni jyla access dila tychya email var massage yein tyla accept karnyasathi

4)jevha tula ""2 person"" cha code ""1 person"" chya ""main branch"" madhi anayacha asan tar hi command tak 

--git fetch
--git switch second branch   ( ani second person cha branch cha nav "second branch") mag tula 1 person ni je kahi code kelai te sagla code tula tuzya main branch madhi disan 
--git switch main 
--git merge second-branch  (ani second person chya branch cha nav)
--git push origin main  


ata merge code github madhi ahe 1 person kad ahe pan 2 person kad nahi mag 




1)2 person  

1)folder create karaychi 
2)jo repository 1 person ni create keli tycya repositery chi url copy karun 2 person chya folder madhi jaun terminal open karaycha mang """git clone (url)""" takaicha  mang 2 person chya folder madhi 1 person chi sange file disan 
3)2 persong tychi swatachi branch create karan pahila """cd repository madhi janar""" nantar terminal madhi """git switch -C second-branch"""  
4)branch kiti ahe check karnyasathi command ""git branch""
git add .
git commit -m "first commit"
git push origin second-branch


5)ata marge code geycha asan tar 
--git switch main
--git fetch 
--git pull 



1la repositery create kar ji repositery keli tyachat (cd foldername) ani (git clone url) kar  
1)ls =>karun kontya file ahet te kalta
2)pwd =>apan kontya path var ahe te kalta
3)cd foldername=> aplyala jya folder madhi jaycha tyaa folder cha nav mhanje ex (cd Internscope)
4)git clone url (url past)
5)git init
6)git add .
7)git commit -m "first commit"
8)git push origin main 