
1)html5 madhi jyasta kai ahe
html (hypertex marcup language)  
hypertex - mahje eka text varun dusra side var jane (<a></a>) hipertext cha kam karta
2)sementric tag 
3)block element
4)metatag
5)ancher tag 
6)attribute




html=>

1)html5 madhi jyasta kai ahe

1)html5 point = audio and video  add ahe
2)"<header>","<fotter>","<section/>" tag add
3)input type  "email" ,"date" ,"number add ahe html madhi 
4)mobile device design html5 feature add kela ahe
5)html5 website fast kela ahe ("baheril pagin kami vaparlya mula")

2)sementric tag (total-9)  main :-("<header>","<footer>","<nav>","<section>","<main> ")

<header> – Header section
<footer> – Footer section
<nav> – Navigation links
<section> – Content section
<main> – Main content area
<article> – Independent content
<aside> – Sidebar or related content
<figure> – Image, chart, or illustration
<figcaption> – Caption for a figure
 
3)block element-("div")("p")("h1,h6")("header,footer") 
purna width gheto

inline element-("span")("button")("img")("a")
purna width ghet nahi

4)metatag -webpage chi mahiti website var thevnyacha kam meta tag karto

5)ancher tag ("<a></a>"  link sathi use hoto)

6)attribute - "id", "class" ,"src","style","alt","href"







